name: AppSec Israel 2023

on: push # Anything will trigger this action

jobs:
  appsecil: # Job Name
    runs-on: ubuntu-latest
    name: Hello World!
    steps:
      - run: echo "Hello AppSec Israel 2023" # Will run this linux command inside the Ubuntu VM (runner)
      - run: id
      - run: uname -a
      - run: env
  owaspzap:
    runs-on: ubuntu-latest # Deploy another VM
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://demo.owasp-juice.shop/'
